name: Parallel-Crypto3 Build and Test on macOS Platforms

on:
  workflow_call:

jobs:
  build-and-test:
    name: "Build and test macOS"
    runs-on: [macos-14]
    steps:
      - name: Checkout Parallel-Crypto3
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # From https://github.com/DeterminateSystems/magic-nix-cache-action
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Run checks
        run: nix flake -L check .?submodules=1#
        env:
          NIX_CONFIG: |
            cores = 0
            max-jobs = 1
