name: Nightly Testing

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-linux-sanitizers:
    name: Linux placeholder testing and sanitize with clang
    uses: ./.github/workflows/clang-sanitizers-linux-nix-check.yml
    if: |
      always() && !cancelled()
    secrets: inherit

  test-linux-proof-producer-debug-gcc:
    name: Gcc debug proof-producer Linux testing
    uses: ./.github/workflows/gcc-debug-proof-producer-nix-check.yml
    if: |
      always() && !cancelled()
    secrets: inherit

  post-telemetry:
    name: Post test results in Open Telemetry format
    runs-on: [self-hosted, Linux, X64, aws_autoscaling]
    needs:
      - test-linux-sanitizers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Post logs to Sig Noz
        run: |
          ls -l -a
          nix build -L .?#checks.x86_64-linux.all-clang-sanitize
          cat ./result/test-logs/test_errors.txt
          export UndefinedBehaviorSanitizer=$(grep UndefinedBehaviorSanitizer result/test-logs/test_errors.txt | wc -l)
          export AddressSanitizer=$(grep AddressSanitizer result/test-logs/test_errors.txt | wc -l)
          export LeakSanitizer=$(grep LeakSanitizer result/test-logs/test_errors.txt | wc -l)
          export OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
          python3 --version
          sudo yum update -y
          sudo yum install -y python3-pip
          pip3 install -r requirements.txt
          /home/ec2-user/.local/bin/opentelemetry-instrument \
            --traces_exporter console,otlp \
            --metrics_exporter console,otlp \
            --logs_exporter console,otlp \
            --service_name nightly-build \
            python3 ./parse_tests.py

