name: Parallel-Crypto3 Build and Test on Linux Platforms

on:
  workflow_call:

jobs:
  build-and-test:
    name: "Build and test Linux"
    runs-on: [self-hosted, Linux, X64, aws_autoscaling]
    steps:
      # https://github.com/actions/checkout/issues/1552
      - name: Clean up after previous checkout
        run: chmod +w -R ${GITHUB_WORKSPACE}; rm -rf ${GITHUB_WORKSPACE}/*;

      - name: Checkout parallel-Crypto3
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Run checks
        run: |
          cd parallel-crypto3
          nix flake update crypto3          
          nix flake -L check .?submodules=1#
        env:
          NIX_CONFIG: |
            cores = 6
            max-jobs = 4
