name: Verify circuit proof

on:
  workflow_call:

jobs:
  produce-proofs:
    name: "Produce and verify proofs"
    runs-on: [self-hosted, Linux, X64, aws_autoscaling]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure
        run: mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_PARALLEL_CRYPTO3_TESTS=FALSE -DPARALLEL_CRYPTO3_ENABLE=TRUE -DBUILD_TESTS=TRUE -DBUILD_CRYPTO3_TESTS=TRUE -G Ninja
        shell: nix develop .#crypto3-tests --command bash -e {0}
      - name: Build
        run: cd build && ninja transpiler_evm_test
        shell: nix develop .#crypto3-tests --command bash -e {0}
      - name: Execute
        run: cd build && ./crypto3/libs/transpiler/test/transpiler_evm_test -- --save-proof-data
        shell: nix develop .#crypto3-tests --command bash -e {0}
      - name: Publish Proofs
        uses: actions/upload-artifact@v4.6.0
        with:
          name: proofs
          path: build/circuit*
          if-no-files-found: error

  verify-proofs:
    name: Verify proofs
    needs:
      - produce-proofs
    if: needs.produce-proofs.result == 'success'
    uses: NilFoundation/evm-placeholder-verification/.github/workflows/verify-proof.yml@873bf83efc9ea50b2fb6d6c4e1f6048f78388d49
    with:
      evm-placeholder-verification-ref: 873bf83efc9ea50b2fb6d6c4e1f6048f78388d49
